#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &

# Wallpaper
feh --bg-scale /home/juan/MEGA/Wallpapers/32.jpg

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#--------------------
## User
#--------------------

# Automount Devices
udiskie -t &
# systray battery icon
cbatticon -u 5 &
